name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker build -t hello-world-app .

      - name: Run Docker container
        run: |
          docker run -d -p 8000:8000 --name hello-world hello-world-app
          sleep 5  # Give server time to start

      - name: Test API response
        run: |
          response=$(curl -s http://localhost:8000/)
          echo "Response: $response"
          if [[ "$response" != *"Hello World!"* ]]; then
            echo "Test failed"
            exit 1
          fi

      - name: Stop Docker container
        run: |
          docker stop hello-world
          docker rm hello-world
